services:
  retr0notes:
    build:
      context: .
    container_name: retr0notes-container
    restart: always
    volumes:
      - ./cache:/workspace/cache
      - ./client:/workspace/client
      - ./db:/workspace/db
      - ./utils:/workspace/utils
    command: ["python3", "/workspace/client/bot.py"]

